### ISSUE TITLE
データが取得できない

### ISSUE THREAD

**Issue by eai04191** [eai04191/status.gochiusa.club#4]
user_information.phpでエラーが出て正しいJSONが出力されずデータが取得出来なくなっている。

**Comment by gaogao-9** [comment]
http://lab.mizle.net/status.gochiusa/user_information.php?id=1
のような、存在しないIDを指定すると、HTMLが部分的に直接吐かれてしまうようです。
今回の例は404の例ですが、他にもTwitterサーバー側が200以外のステータスを返した場合（ビジーな場合など）に、JSONが不正になってしまう可能性があるのでは、と思いました。

面倒ですが、性能のことも考えるとfile_get_contentsではなく、curlでゴリゴリ書いて、レスポンスヘッダまで取得してステータスコードちゃんと確認した方が良いように思いました。
該当部分⇒ https://github.com/eai04191/status.gochiusa.club/blob/master/user_information.php#L12

(ところで余談なんですがstatus.gochiusa.clubから直接叩かずに、lab.mizle.netへ仲介してAPI叩いていますが、問題無いですか？lab.mizle.netは実験サーバーっぽく思ったので気になりました。)
該当部分⇒ https://github.com/eai04191/status.gochiusa.club/blob/master/api.php#L26

**Comment by eai04191** [comment]
見直すとかなりガバガバな実装ですね:bow:
一応file_get_contentsでもステータスコードは取得できるみたいですが、使い勝手が悪そうなのでしっかりcURLで書き直したいと思います。

lab.mizle.netは開発用（ゴミ置き場）で、公開前にstatus.gochiusa.net上を参照するように変更するつもりだったのを変え忘れていた凡ミスです。サーバー自体は変わらないのですがファイルが最新でない可能性があるためこれも修正しておきます。

**Comment by gaogao-9** [comment]
ファイトだよっ！（画像略）
